import fs from 'fs';
import path from 'path';

const filePath = path.join(process.cwd(), 'src/utils/financialTranslator.ts');
let code = fs.readFileSync(filePath, 'utf8');

// Rich additions for SINHALA_TERMS
const extraSinhala = `
  // Government, Political & Regulatory Leadership
  [/\\bPresident Announces\\b/gi, 'ජනාධිපතිවරයා නිවේදනය කරයි'],
  [/\\bPresident\\b/gi, 'ජනාධිපති'],
  [/\\bPrime Minister\\b/gi, 'අග්‍රාමාත්‍යවරයා'],
  [/\\bMinister of Finance\\b/gi, 'මුදල් අමාත්‍යවරයා'],
  [/\\bFinance Minister\\b/gi, 'මුදල් අමාත්‍යවරයා'],
  [/\\bCentral Bank Governor\\b/gi, 'මහ බැංකු අධිපතිවරයා'],
  [/\\bGovernor\\b/gi, 'අධිපතිවරයා'],
  [/\\bTreasury Secretary\\b/gi, 'භාණ්ඩාගාර ලේකම්'],
  [/\\bSecretary\\b/gi, 'ලේකම්'],
  [/\\bMinistry of Finance\\b/gi, 'මුදල් අමාත්‍යාංශය'],
  [/\\bMinistry of Trade\\b/gi, 'වෙළඳ අමාත්‍යාංශය'],
  [/\\bMinistry of Agriculture\\b/gi, 'කෘෂිකර්ම අමාත්‍යාංශය'],
  [/\\bMinistry of Industries\\b/gi, 'කර්මාන්ත අමාත්‍යාංශය'],
  [/\\bMinistry of Foreign Affairs\\b/gi, 'විදේශ කටයුතු අමාත්‍යාංශය'],
  [/\\bMinistry of Transport\\b/gi, 'ප්‍රවාහන අමාත්‍යාංශය'],
  [/\\bMinistry\\b/gi, 'අමාත්‍යාංශය'],
  [/\\bMinister\\b/gi, 'අමාත්‍යවරයා'],
  [/\\bMinisters\\b/gi, 'අමාත්‍යවරුන්'],
  [/\\bCabinet Approves\\b/gi, 'අමාත්‍ය මණ්ඩලය අනුමත කරයි'],
  [/\\bCabinet Decision\\b/gi, 'කැබිනට් තීරණය'],
  [/\\bCabinet Paper\\b/gi, 'කැබිනට් පත්‍රිකාව'],
  [/\\bParliament Approves\\b/gi, 'පාර්ලිමේන්තුව අනුමත කරයි'],
  [/\\bParliament Passes\\b/gi, 'පාර්ලිමේන්තුව සම්මත කරයි'],
  [/\\bGazette Notification\\b/gi, 'ගැසට් නිවේදනය'],
  [/\\bGazette\\b/gi, 'ගැසට් පත්‍රය'],
  [/\\bSupreme Court\\b/gi, 'ශ්‍රේෂ්ඨාධිකරණය'],

  // Reforms, Policies & Taxation
  [/\\bEconomic Reforms\\b/gi, 'ආර්ථික ප්‍රතිසංස්කරණ'],
  [/\\bEconomic Reform\\b/gi, 'ආර්ථික ප්‍රතිසංස්කරණය'],
  [/\\bFiscal Reforms\\b/gi, 'රාජ්‍ය මූල්‍ය ප්‍රතිසංස්කරණ'],
  [/\\bFiscal Reform\\b/gi, 'රාජ්‍ය මූල්‍ය ප්‍රතිසංස්කරණය'],
  [/\\bStructural Reforms\\b/gi, 'ව්‍යුහාත්මක ප්‍රතිසංස්කරණ'],
  [/\\bMonetary Reforms\\b/gi, 'මුදල් ප්‍රතිසංස්කරණ'],
  [/\\bGovernance Reforms\\b/gi, 'පාලන ප්‍රතිසංස්කරණ'],
  [/\\bDirect Tax Adjustments\\b/gi, 'සෘජු බදු සංශෝධන'],
  [/\\bDirect Tax Adjustment\\b/gi, 'සෘජු බදු සංශෝධනය'],
  [/\\bTax Adjustments\\b/gi, 'බදු සංශෝධන'],
  [/\\bDirect Taxes\\b/gi, 'සෘජු බදු'],
  [/\\bDirect Tax\\b/gi, 'සෘජු බද්ද'],
  [/\\bIndirect Taxes\\b/gi, 'වක්‍ර බදු'],
  [/\\bIndirect Tax\\b/gi, 'වක්‍ර බද්ද'],
  [/\\bTax Reforms\\b/gi, 'බදු ප්‍රතිසංස්කරණ'],
  [/\\bIncome Tax\\b/gi, 'ආදායම් බද්ද'],
  [/\\bCorporate Tax\\b/gi, 'ආයතනික බද්ද'],
  [/\\bWithholding Tax\\b/gi, 'රඳවා ගැනීමේ බද්ද (WHT)'],
  [/\\bTax Holiday\\b/gi, 'බදු සහන කාලය'],
  [/\\bTax Exemption\\b/gi, 'බදු නිදහස් කිරීම'],
  [/\\bTax Incentives\\b/gi, 'බදු දිරිගැන්වීම්'],

  // Sectors & Industries
  [/\\bAgricultural Exporters\\b/gi, 'කෘෂිකාර්මික අපනයනකරුවන්'],
  [/\\bAgricultural Exporter\\b/gi, 'කෘෂිකාර්මික අපනයනකරු'],
  [/\\bAgricultural Sector\\b/gi, 'කෘෂිකාර්මික අංශය'],
  [/\\bAgriculture\\b/gi, 'කෘෂිකර්මාන්තය'],
  [/\\bAgricultural\\b/gi, 'කෘෂිකාර්මික'],
  [/\\bExporters\\b/gi, 'අපනයනකරුවන්'],
  [/\\bExporter\\b/gi, 'අපනයනකරු'],
  [/\\bImporters\\b/gi, 'ආනයනකරුවන්'],
  [/\\bImporter\\b/gi, 'ආනයනකරු'],
  [/\\bManufacturers\\b/gi, 'නිෂ්පාදකයින්'],
  [/\\bManufacturer\\b/gi, 'නිෂ්පාදකයා'],
  [/\\bManufacturing Sector\\b/gi, 'නිෂ්පාදන ක්ෂේත්‍රය'],
  [/\\bManufacturing\\b/gi, 'නිෂ්පාදන'],
  [/\\bLocal Manufacturing\\b/gi, 'දේශීය නිෂ්පාදන'],
  [/\\bDomestic Manufacturing\\b/gi, 'දේශීය නිෂ්පාදන ක්ෂේත්‍රය'],
  [/\\bIndustrial Sector\\b/gi, 'කාර්මික අංශය'],
  [/\\bIndustry\\b/gi, 'කර්මාන්ත'],
  [/\\bIndustries\\b/gi, 'කර්මාන්ත'],
  [/\\bServices Sector\\b/gi, 'සේවා අංශය'],
  [/\\bService Sector\\b/gi, 'සේවා අංශය'],
  [/\\bFinancial Sector\\b/gi, 'මූල්‍ය ක්ෂේත්‍රය'],
  [/\\bBanking Sector\\b/gi, 'බැංකු ක්ෂේත්‍රය'],
  [/\\bEnergy Sector\\b/gi, 'බලශක්ති ක්ෂේත්‍රය'],
  [/\\bPower Sector\\b/gi, 'විදුලිබල ක්ෂේත්‍රය'],
  [/\\bTransport Sector\\b/gi, 'ප්‍රවාහන ක්ෂේත්‍රය'],
  [/\\bMaritime Sector\\b/gi, 'සමුද්‍රීය ක්ෂේත්‍රය'],
  [/\\bAviation Sector\\b/gi, 'ගුවන් සේවා ක්ෂේත්‍රය'],
  [/\\bTourism Sector\\b/gi, 'සංචාරක ක්ෂේත්‍රය'],
  [/\\bPrivate Sector\\b/gi, 'පෞද්ගලික අංශය'],
  [/\\bPublic Sector\\b/gi, 'රාජ්‍ය අංශය'],

  // Policy & Actions Phrases
  [/\\bPackage of fiscal reforms\\b/gi, 'රාජ්‍ය මූල්‍ය ප්‍රතිසංස්කරණ පැකේජය'],
  [/\\bMajor package\\b/gi, 'ප්‍රධාන වැඩපිළිවෙලක්'],
  [/\\bDesigned to support\\b/gi, 'සහාය දැක්වීම සඳහා සකස් කරන ලද'],
  [/\\bDesigned to boost\\b/gi, 'ඉහළ නැංවීමේ අරමුණින් සකස් කළ'],
  [/\\bDesigned to\\b/gi, 'ඉලක්ක කරගත්'],
  [/\\bTo support\\b/gi, 'සහාය වීම සඳහා'],
  [/\\bKey economic policies\\b/gi, 'ප්‍රධාන ආර්ථික ප්‍රතිපත්ති'],
  [/\\bEconomic policies\\b/gi, 'ආර්ථික ප්‍රතිපත්ති'],
  [/\\bEconomic policy\\b/gi, 'ආර්ථික ප්‍රතිපත්තිය'],
  [/\\bPolicies\\b/gi, 'ප්‍රතිපත්ති'],
  [/\\bPolicy\\b/gi, 'ප්‍රතිපත්තිය'],
  [/\\bCentral bank policy rate\\b/gi, 'මහ බැංකු ප්‍රතිපත්ති පොලී අනුපාතිකය'],
  [/\\bPolicy rate\\b/gi, 'ප්‍රතිපත්ති පොලී අනුපාතිකය'],
  [/\\bWill remain stable\\b/gi, 'ස්ථාවරව පවතිනු ඇත'],
  [/\\bRemain stable\\b/gi, 'ස්ථාවරව පවතී'],
  [/\\bRemains stable\\b/gi, 'ස්ථාවරව පවතී'],
  [/\\bModerates to target levels\\b/gi, 'ඉලක්කගත මට්ටම් දක්වා මධ්‍යස්ථ වේ'],
  [/\\bModerates to\\b/gi, 'දක්වා මධ්‍යස්ථ වේ'],
  [/\\bModerates\\b/gi, 'මධ්‍යස්ථ මට්ටමකට පැමිණේ'],
  [/\\bModerated\\b/gi, 'මධ්‍යස්ථ විය'],
  [/\\bModerating\\b/gi, 'මධ්‍යස්ථ වෙමින්'],
  [/\\bTarget levels\\b/gi, 'ඉලක්කගත මට්ටම්'],
  [/\\bTarget level\\b/gi, 'ඉලක්කගත මට්ටම'],
  [/\\bTo boost\\b/gi, 'ඉහළ නැංවීම සඳහා'],
  [/\\bBoosts\\b/gi, 'ඉහළ නංවයි'],
  [/\\bBoosted\\b/gi, 'ඉහළ නැංවීය'],
  [/\\bBoost\\b/gi, 'ඉහළ නැංවීම'],
  [/\\bAnnounced\\b/gi, 'ප්‍රකාශයට පත් කළේය'],
  [/\\bAnnounces\\b/gi, 'ප්‍රකාශයට පත් කරයි'],
  [/\\bAnnouncement\\b/gi, 'නිල ප්‍රකාශය'],
  [/\\bAnnouncements\\b/gi, 'නිල ප්‍රකාශ'],
  [/\\bExport Revenue\\b/gi, 'අපනයන ආදායම'],
  [/\\bExport Earnings\\b/gi, 'අපනයන ඉපැයීම්'],
  [/\\bForeign Exchange Reserves\\b/gi, 'විදේශ විනිමය සංචිත'],
  [/\\bForex Reserves\\b/gi, 'විදේශ විනිමය සංචිත'],
`;

// Rich additions for TAMIL_TERMS
const extraTamil = `
  // Government, Political & Regulatory Leadership
  [/\\bPresident Announces\\b/gi, 'ஜனாதிபதி அறிவிக்கிறார்'],
  [/\\bPresident\\b/gi, 'ஜனாதிபதி'],
  [/\\bPrime Minister\\b/gi, 'பிரதமர்'],
  [/\\bMinister of Finance\\b/gi, 'நிதி அமைச்சர்'],
  [/\\bFinance Minister\\b/gi, 'நிதி அமைச்சர்'],
  [/\\bCentral Bank Governor\\b/gi, 'மத்திய வங்கி ஆளுநர்'],
  [/\\bGovernor\\b/gi, 'ஆளுநர்'],
  [/\\bTreasury Secretary\\b/gi, 'திறைசேரி செயலாளர்'],
  [/\\bSecretary\\b/gi, 'செயலாளர்'],
  [/\\bMinistry of Finance\\b/gi, 'நிதி அமைச்சு'],
  [/\\bMinistry of Trade\\b/gi, 'வர்த்தக அமைச்சு'],
  [/\\bMinistry of Agriculture\\b/gi, 'விவசாய அமைச்சு'],
  [/\\bMinistry of Industries\\b/gi, 'கைத்தொழில் அமைச்சு'],
  [/\\bMinistry of Foreign Affairs\\b/gi, 'வெளிவிவகார அமைச்சு'],
  [/\\bMinistry of Transport\\b/gi, 'போக்குவரத்து அமைச்சு'],
  [/\\bMinistry\\b/gi, 'அமைச்சு'],
  [/\\bMinister\\b/gi, 'அமைச்சர்'],
  [/\\bMinisters\\b/gi, 'அமைச்சர்கள்'],
  [/\\bCabinet Approves\\b/gi, 'அமைச்சரவை ஒப்புதல் அளிக்கிறது'],
  [/\\bCabinet Decision\\b/gi, 'அமைச்சரவை முடிவு'],
  [/\\bCabinet Paper\\b/gi, 'அமைச்சரவை பத்திரம்'],
  [/\\bParliament Approves\\b/gi, 'நாடாளுமன்றம் ஒப்புதல் அளிக்கிறது'],
  [/\\bParliament Passes\\b/gi, 'நாடாளுமன்றம் நிறைவேற்றுகிறது'],
  [/\\bGazette Notification\\b/gi, 'வர்த்தமானி அறிவித்தல்'],
  [/\\bGazette\\b/gi, 'வர்த்தமானி'],
  [/\\bSupreme Court\\b/gi, 'உயர் நீதிமன்றம்'],

  // Reforms, Policies & Taxation
  [/\\bEconomic Reforms\\b/gi, 'பொருளாதார சீர்திருத்தங்கள்'],
  [/\\bEconomic Reform\\b/gi, 'பொருளாதார சீர்திருத்தம்'],
  [/\\bFiscal Reforms\\b/gi, 'நிதி சீர்திருத்தங்கள்'],
  [/\\bFiscal Reform\\b/gi, 'நிதி சீர்திருத்தம்'],
  [/\\bStructural Reforms\\b/gi, 'கட்டமைப்பு சீர்திருத்தங்கள்'],
  [/\\bMonetary Reforms\\b/gi, 'பணவியல் சீர்திருத்தங்கள்'],
  [/\\bGovernance Reforms\\b/gi, 'ஆளுகை சீர்திருத்தங்கள்'],
  [/\\bDirect Tax Adjustments\\b/gi, 'நேரடி வரி மாற்றங்கள்'],
  [/\\bDirect Tax Adjustment\\b/gi, 'நேரடி வரி மாற்றம்'],
  [/\\bTax Adjustments\\b/gi, 'வரி மாற்றங்கள்'],
  [/\\bDirect Taxes\\b/gi, 'நேரடி வரிகள்'],
  [/\\bDirect Tax\\b/gi, 'நேரடி வரி'],
  [/\\bIndirect Taxes\\b/gi, 'மறைமுக வரிகள்'],
  [/\\bIndirect Tax\\b/gi, 'மறைமுக வரி'],
  [/\\bTax Reforms\\b/gi, 'வரி சீர்திருத்தங்கள்'],
  [/\\bIncome Tax\\b/gi, 'வருமான வரி'],
  [/\\bCorporate Tax\\b/gi, 'நிறுவன வரி'],
  [/\\bWithholding Tax\\b/gi, 'நிறுத்திவைப்பு வரி (WHT)'],
  [/\\bTax Holiday\\b/gi, 'வரி விடுமுறை'],
  [/\\bTax Exemption\\b/gi, 'வரி விலக்கு'],
  [/\\bTax Incentives\\b/gi, 'வரி சலுகைகள்'],

  // Sectors & Industries
  [/\\bAgricultural Exporters\\b/gi, 'விவசாய ஏற்றுமதியாளர்கள்'],
  [/\\bAgricultural Exporter\\b/gi, 'விவசாய ஏற்றுமதியாளர்'],
  [/\\bAgricultural Sector\\b/gi, 'விவசாயத் துறை'],
  [/\\bAgriculture\\b/gi, 'விவசாயம்'],
  [/\\bAgricultural\\b/gi, 'விவசாய'],
  [/\\bExporters\\b/gi, 'ஏற்றுமதியாளர்கள்'],
  [/\\bExporter\\b/gi, 'ஏற்றுமதியாளர்'],
  [/\\bImporters\\b/gi, 'இறக்குமதியாளர்கள்'],
  [/\\bImporter\\b/gi, 'இறக்குமதியாளர்'],
  [/\\bManufacturers\\b/gi, 'உற்பத்தியாளர்கள்'],
  [/\\bManufacturer\\b/gi, 'உற்பத்தியாளர்'],
  [/\\bManufacturing Sector\\b/gi, 'உற்பத்தித் துறை'],
  [/\\bManufacturing\\b/gi, 'உற்பத்தி'],
  [/\\bLocal Manufacturing\\b/gi, 'உள்நாட்டு உற்பத்தி'],
  [/\\bDomestic Manufacturing\\b/gi, 'உள்நாட்டு உற்பத்தி துறை'],
  [/\\bIndustrial Sector\\b/gi, 'தொழில்துறை'],
  [/\\bIndustry\\b/gi, 'தொழில்துறை'],
  [/\\bIndustries\\b/gi, 'தொழில்கள்'],
  [/\\bServices Sector\\b/gi, 'சேவைத் துறை'],
  [/\\bService Sector\\b/gi, 'சேவைத் துறை'],
  [/\\bFinancial Sector\\b/gi, 'நிதித் துறை'],
  [/\\bBanking Sector\\b/gi, 'வங்கித் துறை'],
  [/\\bEnergy Sector\\b/gi, 'எரிசக்தி துறை'],
  [/\\bPower Sector\\b/gi, 'மின்சாரத் துறை'],
  [/\\bTransport Sector\\b/gi, 'போக்குவரத்துத் துறை'],
  [/\\bMaritime Sector\\b/gi, 'கடல்சார் துறை'],
  [/\\bAviation Sector\\b/gi, 'விமானத் துறை'],
  [/\\bTourism Sector\\b/gi, 'சுற்றுலாத் துறை'],
  [/\\bPrivate Sector\\b/gi, 'தனியார் துறை'],
  [/\\bPublic Sector\\b/gi, 'பொதுத்துறை'],

  // Policy & Actions Phrases
  [/\\bPackage of fiscal reforms\\b/gi, 'நிதி சீர்திருத்த தொகுப்பு'],
  [/\\bMajor package\\b/gi, 'பிரதான தொகுப்பு'],
  [/\\bDesigned to support\\b/gi, 'ஆதரவளிக்கும் வகையில் வடிவமைக்கப்பட்டுள்ளது'],
  [/\\bDesigned to boost\\b/gi, 'அதிகரிக்கும் நோக்கில் உருவாக்கப்பட்டது'],
  [/\\bDesigned to\\b/gi, 'வடிவமைக்கப்பட்டுள்ளது'],
  [/\\bTo support\\b/gi, 'ஆதரவளிக்க'],
  [/\\bKey economic policies\\b/gi, 'முக்கிய பொருளாதார கொள்கைகள்'],
  [/\\bEconomic policies\\b/gi, 'பொருளாதார கொள்கைகள்'],
  [/\\bEconomic policy\\b/gi, 'பொருளாதார கொள்கை'],
  [/\\bPolicies\\b/gi, 'கொள்கைகள்'],
  [/\\bPolicy\\b/gi, 'கொள்கை'],
  [/\\bCentral bank policy rate\\b/gi, 'மத்திய வங்கி கொள்கை வட்டி விகிதம்'],
  [/\\bPolicy rate\\b/gi, 'கொள்கை வட்டி விகிதம்'],
  [/\\bWill remain stable\\b/gi, 'நிலையாக இருக்கும்'],
  [/\\bRemain stable\\b/gi, 'நிலையாக உள்ளது'],
  [/\\bRemains stable\\b/gi, 'நிலையாக உள்ளது'],
  [/\\bModerates to target levels\\b/gi, 'இலக்கு மட்டங்களுக்கு தணிகிறது'],
  [/\\bModerates to\\b/gi, 'வரை தணிகிறது'],
  [/\\bModerates\\b/gi, 'தணிகிறது'],
  [/\\bModerated\\b/gi, 'தணிந்தது'],
  [/\\bModerating\\b/gi, 'தணிந்து வருகிறது'],
  [/\\bTarget levels\\b/gi, 'இலக்கு மட்டங்கள்'],
  [/\\bTarget level\\b/gi, 'இலக்கு மட்டம்'],
  [/\\bTo boost\\b/gi, 'அதிகரிக்க'],
  [/\\bBoosts\\b/gi, 'உயர்த்துகிறது'],
  [/\\bBoosted\\b/gi, 'உயர்த்தியது'],
  [/\\bBoost\\b/gi, 'உயர்வு'],
  [/\\bAnnounced\\b/gi, 'அறிவித்தது'],
  [/\\bAnnounces\\b/gi, 'அறிவிக்கிறது'],
  [/\\bAnnouncement\\b/gi, 'அறிவிப்பு'],
  [/\\bAnnouncements\\b/gi, 'அறிவிப்புகள்'],
  [/\\bExport Revenue\\b/gi, 'ஏற்றுமதி வருவாய்'],
  [/\\bExport Earnings\\b/gi, 'ஏற்றுமதி வருவாய்'],
  [/\\bForeign Exchange Reserves\\b/gi, 'வெளிநாட்டு செலாவணி கையிருப்பு'],
  [/\\bForex Reserves\\b/gi, 'வெளிநாட்டு செலாவணி கையிருப்பு'],
`;

// Insert extraSinhala at top of SINHALA_TERMS
code = code.replace(
  'const SINHALA_TERMS: [RegExp, string][] = [',
  'const SINHALA_TERMS: [RegExp, string][] = [' + extraSinhala
);

// Insert extraTamil at top of TAMIL_TERMS
code = code.replace(
  'const TAMIL_TERMS: [RegExp, string][] = [',
  'const TAMIL_TERMS: [RegExp, string][] = [' + extraTamil
);

fs.writeFileSync(filePath, code, 'utf8');
console.log('Successfully expanded SINHALA_TERMS and TAMIL_TERMS!');
